name: Security Audit

# Run security audits on dependencies
on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  push:
    branches: [main]
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  workflow_dispatch:

jobs:
  audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail on warnings
          # Set to 'deny' to fail on any vulnerabilities
          # Set to 'warn' to only warn on vulnerabilities
          ignore: []
